// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/code.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/code.go -package=repomocks -destination=internal/repository/mocks/code.mock.go
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICodeRepository is a mock of ICodeRepository interface.
type MockICodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICodeRepositoryMockRecorder
}

// MockICodeRepositoryMockRecorder is the mock recorder for MockICodeRepository.
type MockICodeRepositoryMockRecorder struct {
	mock *MockICodeRepository
}

// NewMockICodeRepository creates a new mock instance.
func NewMockICodeRepository(ctrl *gomock.Controller) *MockICodeRepository {
	mock := &MockICodeRepository{ctrl: ctrl}
	mock.recorder = &MockICodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICodeRepository) EXPECT() *MockICodeRepositoryMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockICodeRepository) Set(ctx context.Context, biz, phone, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, biz, phone, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockICodeRepositoryMockRecorder) Set(ctx, biz, phone, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockICodeRepository)(nil).Set), ctx, biz, phone, code)
}

// Verify mocks base method.
func (m *MockICodeRepository) Verify(ctx context.Context, biz, phone, inputCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, inputCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockICodeRepositoryMockRecorder) Verify(ctx, biz, phone, inputCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockICodeRepository)(nil).Verify), ctx, biz, phone, inputCode)
}
