apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
  labels:
    app: webook-mysql-claim
spec:
  storageClassName: webook-mysql-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  