apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pv
spec:
  storageClassName: webook-mysql-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/webook/mysql"