// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/lcsin/goprojets/webook/internal/handler"
	"github.com/lcsin/goprojets/webook/internal/repository"
	"github.com/lcsin/goprojets/webook/internal/repository/cache"
	"github.com/lcsin/goprojets/webook/internal/repository/dao"
	"github.com/lcsin/goprojets/webook/internal/service"
	"github.com/lcsin/goprojets/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDB()
	iUserDAO := dao.NewUserDAO(db)
	iUserCache := cache.NewUserCache(cmdable)
	iUserRepository := repository.NewUserRepository(iUserDAO, iUserCache)
	iUserService := service.NewUserService(iUserRepository)
	iCodeCache := cache.NewCodeCache(cmdable)
	iCodeRepository := repository.NewCodeRepository(iCodeCache)
	smsService := ioc.InitSMSService(cmdable)
	iCodeService := service.NewCodeService(iCodeRepository, smsService)
	userHandler := handler.NewUserHandler(iUserService, iCodeService)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
