// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/code.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/code.go -package=svcmocks -destination=internal/service/mocks/code.mock.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICodeService is a mock of ICodeService interface.
type MockICodeService struct {
	ctrl     *gomock.Controller
	recorder *MockICodeServiceMockRecorder
}

// MockICodeServiceMockRecorder is the mock recorder for MockICodeService.
type MockICodeServiceMockRecorder struct {
	mock *MockICodeService
}

// NewMockICodeService creates a new mock instance.
func NewMockICodeService(ctrl *gomock.Controller) *MockICodeService {
	mock := &MockICodeService{ctrl: ctrl}
	mock.recorder = &MockICodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICodeService) EXPECT() *MockICodeServiceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockICodeService) Send(ctx context.Context, biz, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, biz, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockICodeServiceMockRecorder) Send(ctx, biz, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockICodeService)(nil).Send), ctx, biz, phone)
}

// Verify mocks base method.
func (m *MockICodeService) Verify(ctx context.Context, biz, phone, inputCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, inputCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockICodeServiceMockRecorder) Verify(ctx, biz, phone, inputCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockICodeService)(nil).Verify), ctx, biz, phone, inputCode)
}
