apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-mysql-pv
spec:
  storageClassName: k8s-mysql-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/mysql"