apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mysql
  labels:
    app: k8s-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mysql
  template:
    metadata:
      name: k8s-mysql
      labels:
        app: k8s-mysql
    spec:
      containers:
        - name: k8s-mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            # 对应到MySQL数据存储路径
            - mountPath: /var/lib/mysql
              name: mysql-storage
      restartPolicy: Always
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: k8s-mysql-claim
      