apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-mysql-claim
  labels:
    app: k8s-mysql-claim
spec:
  storageClassName: k8s-mysql-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  